In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr1=np.array([[1,2,3,4,5],[7,8,9,10,11],[2,3,4,7,8]])
arr1

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [ 2,  3,  4,  7,  8]])

In [ ]:
type(arr1)

numpy.ndarray

In [ ]:
arr1.ndim

2

In [ ]:
arr.size


5

In [ ]:
arr1.size

15

In [ ]:
arr.shape

(5,)

In [ ]:
arr1.shape

(3, 5)

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr2= np.arange(1,10)

In [ ]:
print(arr2)

[1 2 3 4 5 6 7 8 9]


In [ ]:
m1 = np.reshape(arr2,(3,3))
print(m1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.empty((3,4))

array([[0.00000000e+000, 6.79038653e-313, 2.54639495e-312,
        2.14321575e-312],
       [2.46151512e-312, 1.78247646e-312, 2.37663529e-312,
        1.46417710e-312],
       [2.41907520e-312, 2.41907520e-312, 2.86558075e-322,
        0.00000000e+000]])

In [ ]:
np.transpose(m1,axes=None)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
import numpy as np

In [ ]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Addition of two arrays
arr1 +arr2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.add(arr1, arr2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
#Subtraction of two array 
print(arr1 -arr2)

print(np.subtract(arr1,arr2))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
print(arr1 * arr2)

print(np.multiply(arr1,arr2))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
print(arr1 @ arr2)
print(arr1.dot(arr2))

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
#Sum
np.sum(arr1)

45

In [ ]:
np.mean(arr1)

5.0

In [ ]:
#Square root
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [ ]:
#Standerd Deviation
np.std(arr1)

2.581988897471611

In [ ]:
#Exponential value
	
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])